// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/transport/tcp/server.go

// Package mock_tcp is a generated GoMock package.
package mock_tcp

import (
	net "net"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockHandler is a mock of Handler interface.
type MockHandler struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerMockRecorder
}

// MockHandlerMockRecorder is the mock recorder for MockHandler.
type MockHandlerMockRecorder struct {
	mock *MockHandler
}

// NewMockHandler creates a new mock instance.
func NewMockHandler(ctrl *gomock.Controller) *MockHandler {
	mock := &MockHandler{ctrl: ctrl}
	mock.recorder = &MockHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandler) EXPECT() *MockHandlerMockRecorder {
	return m.recorder
}

// OpenNewConnection mocks base method.
func (m *MockHandler) OpenNewConnection(conn net.Conn) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OpenNewConnection", conn)
}

// OpenNewConnection indicates an expected call of OpenNewConnection.
func (mr *MockHandlerMockRecorder) OpenNewConnection(conn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenNewConnection", reflect.TypeOf((*MockHandler)(nil).OpenNewConnection), conn)
}
